from django.core.management.base import BaseCommand
from django.utils.text import slugify
from apps.catalog.models import Category, Product
from apps.inventory.models import Inventory


class Command(BaseCommand):
    help = 'Seed the database with sample categories and products'

    def handle(self, *args, **kwargs):
        self.stdout.write('Seeding catalog...')

        # Categories
        categories_data = [
            {'name': 'Fruits & Vegetables', 'display_order': 1},
            {'name': 'Dairy & Eggs',        'display_order': 2},
            {'name': 'Snacks & Beverages',  'display_order': 3},
            {'name': 'Staples & Grains',    'display_order': 4},
            {'name': 'Personal Care',       'display_order': 5},
            {'name': 'Household',           'display_order': 6},
        ]

        categories = {}
        for data in categories_data:
            cat, created = Category.objects.get_or_create(
                name=data['name'],
                defaults={
                    'slug': slugify(data['name']),
                    'display_order': data['display_order'],
                    'is_active': True,
                }
            )
            categories[data['name']] = cat
            if created:
                self.stdout.write(f'  Created category: {cat.name}')

        # Products
        products_data = [

            # ── Fruits & Vegetables ──────────────────────────────────────
            {
                'category': 'Fruits & Vegetables',
                'name': 'Fresh Bananas',
                'brand_name': 'Farm Fresh',
                'short_description': 'Sweet and ripe bananas, rich in potassium',
                'sku': 'FV-BAN-001',
                'barcode': '8901234567890',
                'base_price': 60.00,  'selling_price': 49.00,
                'unit': 'dozen', 'is_featured': True,
                'tags': ['fresh', 'fruit', 'organic'],
            },
            {
                'category': 'Fruits & Vegetables',
                'name': 'Fresh Tomatoes',
                'brand_name': 'Farm Fresh',
                'short_description': 'Juicy red tomatoes, perfect for cooking',
                'sku': 'FV-TOM-001',
                'barcode': '8901234567891',
                'base_price': 40.00,  'selling_price': 35.00,
                'unit': '500g', 'is_featured': False,
                'tags': ['fresh', 'vegetable'],
            },
            {
                'category': 'Fruits & Vegetables',
                'name': 'Fresh Onions',
                'brand_name': 'Farm Fresh',
                'short_description': 'Fresh red onions, essential for every kitchen',
                'sku': 'FV-ONI-001',
                'barcode': '8901234567902',
                'base_price': 50.00,  'selling_price': 45.00,
                'unit': '1kg', 'is_featured': False,
                'tags': ['fresh', 'vegetable'],
            },
            {
                'category': 'Fruits & Vegetables',
                'name': 'Fresh Potatoes',
                'brand_name': 'Farm Fresh',
                'short_description': 'Farm-fresh potatoes, great for curries and fries',
                'sku': 'FV-POT-001',
                'barcode': '8901234567903',
                'base_price': 35.00,  'selling_price': 30.00,
                'unit': '1kg', 'is_featured': False,
                'tags': ['fresh', 'vegetable'],
            },
            {
                'category': 'Fruits & Vegetables',
                'name': 'Fresh Apples',
                'brand_name': 'Farm Fresh',
                'short_description': 'Crisp and juicy red apples from Himachal',
                'sku': 'FV-APP-001',
                'barcode': '8901234567904',
                'base_price': 180.00, 'selling_price': 149.00,
                'unit': '1kg', 'is_featured': True,
                'tags': ['fresh', 'fruit'],
            },
            {
                'category': 'Fruits & Vegetables',
                'name': 'Fresh Spinach',
                'brand_name': 'Farm Fresh',
                'short_description': 'Tender green spinach leaves, rich in iron',
                'sku': 'FV-SPI-001',
                'barcode': '8901234567905',
                'base_price': 30.00,  'selling_price': 25.00,
                'unit': '250g', 'is_featured': False,
                'tags': ['fresh', 'vegetable', 'green'],
            },
            {
                'category': 'Fruits & Vegetables',
                'name': 'Fresh Carrots',
                'brand_name': 'Farm Fresh',
                'short_description': 'Crunchy orange carrots, high in vitamin A',
                'sku': 'FV-CAR-001',
                'barcode': '8901234567906',
                'base_price': 45.00,  'selling_price': 39.00,
                'unit': '500g', 'is_featured': False,
                'tags': ['fresh', 'vegetable'],
            },
            {
                'category': 'Fruits & Vegetables',
                'name': 'Fresh Mangoes',
                'brand_name': 'Farm Fresh',
                'short_description': 'Sweet Alphonso mangoes, the king of fruits',
                'sku': 'FV-MAN-001',
                'barcode': '8901234567907',
                'base_price': 250.00, 'selling_price': 199.00,
                'unit': '1kg', 'is_featured': True,
                'tags': ['fresh', 'fruit', 'seasonal'],
            },
            {
                'category': 'Fruits & Vegetables',
                'name': 'Fresh Cauliflower',
                'brand_name': 'Farm Fresh',
                'short_description': 'White cauliflower, perfect for aloo gobi',
                'sku': 'FV-CAU-001',
                'barcode': '8901234567908',
                'base_price': 55.00,  'selling_price': 49.00,
                'unit': '500g', 'is_featured': False,
                'tags': ['fresh', 'vegetable'],
            },

            # ── Dairy & Eggs ─────────────────────────────────────────────
            {
                'category': 'Dairy & Eggs',
                'name': 'Amul Full Cream Milk',
                'brand_name': 'Amul',
                'short_description': 'Pure and fresh full cream milk',
                'sku': 'DE-MILK-001',
                'barcode': '8901234567892',
                'base_price': 68.00,  'selling_price': 64.00,
                'unit': '1L', 'is_featured': True,
                'tags': ['dairy', 'milk'],
            },
            {
                'category': 'Dairy & Eggs',
                'name': 'Farm Eggs',
                'brand_name': 'Country Eggs',
                'short_description': 'Fresh farm eggs, rich in protein',
                'sku': 'DE-EGG-001',
                'barcode': '8901234567893',
                'base_price': 90.00,  'selling_price': 84.00,
                'unit': '12 pcs', 'is_featured': False,
                'tags': ['eggs', 'protein'],
            },
            {
                'category': 'Dairy & Eggs',
                'name': 'Amul Butter',
                'brand_name': 'Amul',
                'short_description': 'Pasteurised butter, perfect for cooking and spreading',
                'sku': 'DE-BUT-001',
                'barcode': '8901234567896',
                'base_price': 55.00,  'selling_price': 52.00,
                'unit': '100g', 'is_featured': False,
                'tags': ['dairy', 'butter'],
            },
            {
                'category': 'Dairy & Eggs',
                'name': 'Amul Paneer',
                'brand_name': 'Amul',
                'short_description': 'Fresh cottage cheese, great for curries',
                'sku': 'DE-PAN-001',
                'barcode': '8901234567909',
                'base_price': 90.00,  'selling_price': 85.00,
                'unit': '200g', 'is_featured': True,
                'tags': ['dairy', 'paneer'],
            },
            {
                'category': 'Dairy & Eggs',
                'name': 'Nestle Dahi',
                'brand_name': 'Nestle',
                'short_description': 'Thick and creamy curd',
                'sku': 'DE-DAH-001',
                'barcode': '8901234567910',
                'base_price': 45.00,  'selling_price': 42.00,
                'unit': '400g', 'is_featured': False,
                'tags': ['dairy', 'curd', 'yogurt'],
            },
            {
                'category': 'Dairy & Eggs',
                'name': 'Amul Cheese Slices',
                'brand_name': 'Amul',
                'short_description': 'Processed cheese slices for sandwiches and burgers',
                'sku': 'DE-CHE-001',
                'barcode': '8901234567911',
                'base_price': 110.00, 'selling_price': 99.00,
                'unit': '200g', 'is_featured': False,
                'tags': ['dairy', 'cheese'],
            },
            {
                'category': 'Dairy & Eggs',
                'name': 'Mother Dairy Lassi',
                'brand_name': 'Mother Dairy',
                'short_description': 'Sweet and refreshing mango lassi',
                'sku': 'DE-LAS-001',
                'barcode': '8901234567912',
                'base_price': 30.00,  'selling_price': 30.00,
                'unit': '200ml', 'is_featured': False,
                'tags': ['dairy', 'lassi', 'drink'],
            },

            # ── Snacks & Beverages ────────────────────────────────────────
            {
                'category': 'Snacks & Beverages',
                'name': "Lay's Classic Salted",
                'brand_name': "Lay's",
                'short_description': 'Classic salted potato chips',
                'sku': 'SB-LAY-001',
                'barcode': '8901234567894',
                'base_price': 30.00,  'selling_price': 30.00,
                'unit': '26g', 'is_featured': True,
                'tags': ['snacks', 'chips'],
            },
            {
                'category': 'Snacks & Beverages',
                'name': 'Maggi 2-Minute Noodles',
                'brand_name': 'Maggi',
                'short_description': 'Classic masala instant noodles',
                'sku': 'SB-MAG-001',
                'barcode': '8901234567898',
                'base_price': 14.00,  'selling_price': 14.00,
                'unit': '70g', 'is_featured': True,
                'tags': ['noodles', 'snacks', 'instant'],
            },
            {
                'category': 'Snacks & Beverages',
                'name': 'Coca Cola',
                'brand_name': 'Coca Cola',
                'short_description': 'Refreshing cola drink',
                'sku': 'SB-COK-001',
                'barcode': '8901234567899',
                'base_price': 40.00,  'selling_price': 40.00,
                'unit': '750ml', 'is_featured': False,
                'tags': ['beverages', 'cold drink', 'soda'],
            },
            {
                'category': 'Snacks & Beverages',
                'name': 'Parle-G Biscuits',
                'brand_name': 'Parle',
                'short_description': 'The original glucose biscuits',
                'sku': 'SB-PAR-001',
                'barcode': '8901234567913',
                'base_price': 10.00,  'selling_price': 10.00,
                'unit': '100g', 'is_featured': False,
                'tags': ['biscuits', 'snacks'],
            },
            {
                'category': 'Snacks & Beverages',
                'name': 'Haldiram Aloo Bhujia',
                'brand_name': 'Haldiram',
                'short_description': 'Crispy and spicy potato bhujia',
                'sku': 'SB-HAL-001',
                'barcode': '8901234567914',
                'base_price': 50.00,  'selling_price': 45.00,
                'unit': '150g', 'is_featured': False,
                'tags': ['snacks', 'namkeen'],
            },
            {
                'category': 'Snacks & Beverages',
                'name': 'Tropicana Orange Juice',
                'brand_name': 'Tropicana',
                'short_description': '100% pure orange juice with pulp',
                'sku': 'SB-TRO-001',
                'barcode': '8901234567915',
                'base_price': 99.00,  'selling_price': 89.00,
                'unit': '1L', 'is_featured': True,
                'tags': ['juice', 'beverages', 'healthy'],
            },
            {
                'category': 'Snacks & Beverages',
                'name': 'Kurkure Masala Munch',
                'brand_name': 'Kurkure',
                'short_description': 'Crunchy corn puffs with masala flavour',
                'sku': 'SB-KUR-001',
                'barcode': '8901234567916',
                'base_price': 20.00,  'selling_price': 20.00,
                'unit': '90g', 'is_featured': False,
                'tags': ['snacks', 'puffs'],
            },
            {
                'category': 'Snacks & Beverages',
                'name': 'Lipton Green Tea',
                'brand_name': 'Lipton',
                'short_description': 'Refreshing green tea bags',
                'sku': 'SB-LIP-001',
                'barcode': '8901234567917',
                'base_price': 149.00, 'selling_price': 130.00,
                'unit': '25 bags', 'is_featured': False,
                'tags': ['tea', 'green tea', 'healthy'],
            },
            {
                'category': 'Snacks & Beverages',
                'name': 'Red Bull Energy Drink',
                'brand_name': 'Red Bull',
                'short_description': 'Energy drink that gives you wings',
                'sku': 'SB-RED-001',
                'barcode': '8901234567918',
                'base_price': 125.00, 'selling_price': 115.00,
                'unit': '250ml', 'is_featured': False,
                'tags': ['energy drink', 'beverages'],
            },
            {
                'category': 'Snacks & Beverages',
                'name': 'Britannia Good Day',
                'brand_name': 'Britannia',
                'short_description': 'Butter cookies with cashew',
                'sku': 'SB-BRI-001',
                'barcode': '8901234567919',
                'base_price': 35.00,  'selling_price': 35.00,
                'unit': '100g', 'is_featured': False,
                'tags': ['biscuits', 'cookies', 'snacks'],
            },

            # ── Staples & Grains ──────────────────────────────────────────
            {
                'category': 'Staples & Grains',
                'name': 'Basmati Rice',
                'brand_name': 'India Gate',
                'short_description': 'Premium long grain basmati rice',
                'sku': 'SG-RICE-001',
                'barcode': '8901234567895',
                'base_price': 299.00, 'selling_price': 259.00,
                'unit': '1kg', 'is_featured': True,
                'tags': ['rice', 'staples', 'grains'],
            },
            {
                'category': 'Staples & Grains',
                'name': 'Aashirvaad Whole Wheat Atta',
                'brand_name': 'Aashirvaad',
                'short_description': 'Whole wheat flour for soft rotis',
                'sku': 'SG-ATT-001',
                'barcode': '8901234567897',
                'base_price': 280.00, 'selling_price': 265.00,
                'unit': '5kg', 'is_featured': True,
                'tags': ['flour', 'atta', 'staples'],
            },
            {
                'category': 'Staples & Grains',
                'name': 'Toor Dal',
                'brand_name': 'Fortune',
                'short_description': 'Premium yellow lentils for dal tadka',
                'sku': 'SG-DAL-001',
                'barcode': '8901234567920',
                'base_price': 165.00, 'selling_price': 155.00,
                'unit': '1kg', 'is_featured': False,
                'tags': ['dal', 'lentils', 'staples'],
            },
            {
                'category': 'Staples & Grains',
                'name': 'Chana Dal',
                'brand_name': 'Fortune',
                'short_description': 'Split chickpeas, rich in protein',
                'sku': 'SG-CDA-001',
                'barcode': '8901234567921',
                'base_price': 140.00, 'selling_price': 129.00,
                'unit': '1kg', 'is_featured': False,
                'tags': ['dal', 'lentils', 'staples'],
            },
            {
                'category': 'Staples & Grains',
                'name': 'Sona Masoori Rice',
                'brand_name': 'Daawat',
                'short_description': 'Light and fluffy everyday rice',
                'sku': 'SG-SMR-001',
                'barcode': '8901234567922',
                'base_price': 89.00,  'selling_price': 79.00,
                'unit': '1kg', 'is_featured': False,
                'tags': ['rice', 'staples'],
            },
            {
                'category': 'Staples & Grains',
                'name': 'Sunflower Oil',
                'brand_name': 'Saffola',
                'short_description': 'Refined sunflower oil, heart healthy',
                'sku': 'SG-OIL-001',
                'barcode': '8901234567923',
                'base_price': 180.00, 'selling_price': 165.00,
                'unit': '1L', 'is_featured': False,
                'tags': ['oil', 'cooking', 'staples'],
            },
            {
                'category': 'Staples & Grains',
                'name': 'Tata Salt',
                'brand_name': 'Tata',
                'short_description': 'Iodised salt for healthy cooking',
                'sku': 'SG-SAL-001',
                'barcode': '8901234567924',
                'base_price': 28.00,  'selling_price': 25.00,
                'unit': '1kg', 'is_featured': False,
                'tags': ['salt', 'staples'],
            },
            {
                'category': 'Staples & Grains',
                'name': 'Tata Tea Gold',
                'brand_name': 'Tata Tea',
                'short_description': 'Premium blend of Assam tea',
                'sku': 'SG-TEA-001',
                'barcode': '8901234567925',
                'base_price': 299.00, 'selling_price': 275.00,
                'unit': '500g', 'is_featured': True,
                'tags': ['tea', 'beverages', 'staples'],
            },
            {
                'category': 'Staples & Grains',
                'name': 'Nescafe Classic Coffee',
                'brand_name': 'Nescafe',
                'short_description': 'Rich and aromatic instant coffee',
                'sku': 'SG-COF-001',
                'barcode': '8901234567926',
                'base_price': 220.00, 'selling_price': 199.00,
                'unit': '100g', 'is_featured': False,
                'tags': ['coffee', 'beverages', 'staples'],
            },
            {
                'category': 'Staples & Grains',
                'name': 'MDH Garam Masala',
                'brand_name': 'MDH',
                'short_description': 'Aromatic blend of spices for Indian cooking',
                'sku': 'SG-MAS-001',
                'barcode': '8901234567927',
                'base_price': 80.00,  'selling_price': 72.00,
                'unit': '100g', 'is_featured': False,
                'tags': ['spices', 'masala', 'staples'],
            },

            # ── Personal Care ─────────────────────────────────────────────
            {
                'category': 'Personal Care',
                'name': 'Dove Beauty Soap',
                'brand_name': 'Dove',
                'short_description': 'Moisturising beauty soap with 1/4 cream',
                'sku': 'PC-DOV-001',
                'barcode': '8901234567900',
                'base_price': 48.00,  'selling_price': 45.00,
                'unit': '100g', 'is_featured': False,
                'tags': ['soap', 'personal care', 'skin care'],
            },
            {
                'category': 'Personal Care',
                'name': 'Colgate Strong Teeth',
                'brand_name': 'Colgate',
                'short_description': 'Toothpaste with calcium and minerals',
                'sku': 'PC-COL-001',
                'barcode': '8901234567928',
                'base_price': 89.00,  'selling_price': 79.00,
                'unit': '200g', 'is_featured': False,
                'tags': ['toothpaste', 'oral care', 'personal care'],
            },
            {
                'category': 'Personal Care',
                'name': 'Head & Shoulders Shampoo',
                'brand_name': 'Head & Shoulders',
                'short_description': 'Anti-dandruff shampoo for healthy scalp',
                'sku': 'PC-HNS-001',
                'barcode': '8901234567929',
                'base_price': 349.00, 'selling_price': 299.00,
                'unit': '340ml', 'is_featured': True,
                'tags': ['shampoo', 'hair care', 'personal care'],
            },
            {
                'category': 'Personal Care',
                'name': 'Nivea Body Lotion',
                'brand_name': 'Nivea',
                'short_description': 'Deep moisture body lotion for soft skin',
                'sku': 'PC-NIV-001',
                'barcode': '8901234567930',
                'base_price': 220.00, 'selling_price': 199.00,
                'unit': '200ml', 'is_featured': False,
                'tags': ['lotion', 'skin care', 'personal care'],
            },
            {
                'category': 'Personal Care',
                'name': 'Gillette Mach3 Razor',
                'brand_name': 'Gillette',
                'short_description': '3-blade razor for a smooth shave',
                'sku': 'PC-GIL-001',
                'barcode': '8901234567931',
                'base_price': 199.00, 'selling_price': 175.00,
                'unit': '1 pc', 'is_featured': False,
                'tags': ['razor', 'shaving', 'personal care'],
            },
            {
                'category': 'Personal Care',
                'name': 'Whisper Ultra Pads',
                'brand_name': 'Whisper',
                'short_description': 'Ultra thin sanitary pads with wings',
                'sku': 'PC-WHI-001',
                'barcode': '8901234567932',
                'base_price': 89.00,  'selling_price': 79.00,
                'unit': '15 pcs', 'is_featured': False,
                'tags': ['hygiene', 'personal care'],
            },
            {
                'category': 'Personal Care',
                'name': 'Dettol Hand Sanitizer',
                'brand_name': 'Dettol',
                'short_description': 'Kills 99.9% germs instantly',
                'sku': 'PC-DET-001',
                'barcode': '8901234567933',
                'base_price': 99.00,  'selling_price': 89.00,
                'unit': '200ml', 'is_featured': False,
                'tags': ['sanitizer', 'hygiene', 'personal care'],
            },
            {
                'category': 'Personal Care',
                'name': 'Axe Dark Temptation Deodorant',
                'brand_name': 'Axe',
                'short_description': 'Long lasting chocolate scented deodorant',
                'sku': 'PC-AXE-001',
                'barcode': '8901234567934',
                'base_price': 175.00, 'selling_price': 155.00,
                'unit': '150ml', 'is_featured': False,
                'tags': ['deodorant', 'personal care'],
            },

            # ── Household ─────────────────────────────────────────────────
            {
                'category': 'Household',
                'name': 'Vim Dishwash Liquid',
                'brand_name': 'Vim',
                'short_description': 'Cuts grease effectively, fresh lime fragrance',
                'sku': 'HH-VIM-001',
                'barcode': '8901234567901',
                'base_price': 99.00,  'selling_price': 89.00,
                'unit': '500ml', 'is_featured': False,
                'tags': ['household', 'cleaning', 'dishwash'],
            },
            {
                'category': 'Household',
                'name': 'Surf Excel Matic',
                'brand_name': 'Surf Excel',
                'short_description': 'Detergent for front load washing machines',
                'sku': 'HH-SUR-001',
                'barcode': '8901234567935',
                'base_price': 349.00, 'selling_price': 310.00,
                'unit': '1kg', 'is_featured': True,
                'tags': ['detergent', 'laundry', 'household'],
            },
            {
                'category': 'Household',
                'name': 'Colin Glass Cleaner',
                'brand_name': 'Colin',
                'short_description': 'Streak-free glass and surface cleaner',
                'sku': 'HH-COL-001',
                'barcode': '8901234567936',
                'base_price': 129.00, 'selling_price': 115.00,
                'unit': '500ml', 'is_featured': False,
                'tags': ['cleaner', 'household'],
            },
            {
                'category': 'Household',
                'name': 'Good Knight Mosquito Coil',
                'brand_name': 'Good Knight',
                'short_description': 'All-night mosquito protection coils',
                'sku': 'HH-GKN-001',
                'barcode': '8901234567937',
                'base_price': 40.00,  'selling_price': 38.00,
                'unit': '10 coils', 'is_featured': False,
                'tags': ['mosquito', 'household', 'protection'],
            },
            {
                'category': 'Household',
                'name': 'Harpic Toilet Cleaner',
                'brand_name': 'Harpic',
                'short_description': 'Powerful toilet bowl cleaner and disinfectant',
                'sku': 'HH-HAR-001',
                'barcode': '8901234567938',
                'base_price': 89.00,  'selling_price': 79.00,
                'unit': '500ml', 'is_featured': False,
                'tags': ['cleaner', 'household', 'toilet'],
            },
            {
                'category': 'Household',
                'name': 'Lizol Floor Cleaner',
                'brand_name': 'Lizol',
                'short_description': 'Kills 99.9% germs on floors',
                'sku': 'HH-LIZ-001',
                'barcode': '8901234567939',
                'base_price': 149.00, 'selling_price': 135.00,
                'unit': '500ml', 'is_featured': False,
                'tags': ['floor cleaner', 'household', 'cleaning'],
            },
            {
                'category': 'Household',
                'name': 'Scotch-Brite Scrub Pad',
                'brand_name': 'Scotch-Brite',
                'short_description': 'Heavy duty scrubbing pads for utensils',
                'sku': 'HH-SCO-001',
                'barcode': '8901234567940',
                'base_price': 35.00,  'selling_price': 32.00,
                'unit': '3 pcs', 'is_featured': False,
                'tags': ['scrub', 'kitchen', 'household'],
            },
            {
                'category': 'Household',
                'name': 'Aluminium Foil',
                'brand_name': 'Hindalco',
                'short_description': 'Heavy duty aluminium foil for cooking and storage',
                'sku': 'HH-ALU-001',
                'barcode': '8901234567941',
                'base_price': 89.00,  'selling_price': 79.00,
                'unit': '9m roll', 'is_featured': False,
                'tags': ['kitchen', 'household', 'storage'],
            },
        ]

        created_count = 0
        for data in products_data:
            cat_name = data.pop('category')
            category = categories[cat_name]
            product, created = Product.objects.get_or_create(
                sku=data['sku'],
                defaults={
                    **data,
                    'slug': slugify(data['name']),
                    'category': category,
                    'is_active': True,
                }
            )
            if created:
                Inventory.objects.get_or_create(
                    product=product,
                    defaults={
                        'quantity_in_stock': 100,
                        'low_stock_threshold': 10,
                    }
                )
                created_count += 1
                self.stdout.write(f'  Created: {product.name}')

        self.stdout.write(
            self.style.SUCCESS(
                f'\nDone! {created_count} new products created. '
                f'Total products: {Product.objects.count()}'
            )
        )